FROM debian:bookworm-slim as stage1
RUN apt-get update && apt install -y libboost-all-dev=1.74.0.3 \
libpqxx-dev=6.4.5-2 git=1:2.34.1-1 g++=4:11.2.0-2 make=4.3-4.1 cmake
COPY . .
run ./build.sh -c


FROM debian:bookworm-slim
RUN apt-get update && apt install -y libpqxx-dev=6.4.5-2 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
COPY --from=stage1 /build/target/Desbordante_cpp_consumer /
COPY --from=stage1 /build/target/logging.conf /
COPY --from=stage1 /build/target/inputData/ /build/target/inputData/
ENTRYPOINT ["./Desbordante_cpp_consumer"]
CMD ["taskId_placeholder"]