FROM debian:bookworm-slim as stage1
RUN apt-get update && apt install -y libboost-all-dev \
libpqxx-dev git g++ make cmake
COPY . .
run ./build.sh -c


FROM debian:bookworm-slim
RUN apt-get update && apt install -y libpqxx-dev && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
COPY --from=stage1 /build/target/Desbordante_cpp_consumer /
COPY --from=stage1 /build/target/logging.conf /
ENTRYPOINT ["./Desbordante_cpp_consumer"]
CMD ["taskId_placeholder"]