FROM mirror.gcr.io/debian:bullseye-slim
RUN apt-get update && apt-get -y install python3 make g++ npm curl
RUN npm install --global yarn
RUN npm install -g n
RUN n 16.14.2
COPY server/package.json server/package.json
COPY server/yarn.lock server/yarn.lock
WORKDIR /server/
RUN yarn
COPY server/ /server/
RUN yarn build
ENTRYPOINT ["yarn", "start"]
