FROM debian:bookworm-slim
RUN apt-get update && apt-get -y install yarnpkg=1.22.10+~cs22.25.14-8 python3=3.9.7-1 make g++
COPY server/ server/
WORKDIR server/
RUN yarnpkg global add node-gyp --ignore-engines
RUN yarnpkg --ignore-engines
ENTRYPOINT ["yarnpkg", "start"]