FROM node:17-alpine
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev > /dev/null 2>&1
COPY cms/package.json cms/package.json
COPY cms/yarn.lock cms/yarn.lock
WORKDIR /cms/
RUN yarn
COPY cms/ /cms/
RUN yarn build
ENTRYPOINT ["yarn", "start"]
