FROM debian:bookworm-slim
RUN apt-get update && apt-get -y install python3 make g++ npm curl
RUN npm install --global yarn
RUN npm install -g n
RUN n stable
COPY server/package.json server/package.json
WORKDIR /server/
RUN yarn
COPY server/ /server/
RUN yarn build
ENTRYPOINT ["yarn", "start"]