FROM mirror.gcr.io/debian:bullseye-slim

### ############ ###
### INSTALLATION ###
### ############ ###
# pre config apt
RUN echo "postfix postfix/main_mailer_type string Internet site" > preseed.txt && \
    echo "postfix postfix/mailname string desbordante.local" >> preseed.txt
# load pre-config for apt
RUN debconf-set-selections preseed.txt
RUN apt-get -y update \
 && apt-get -y install postfix mailutils rsyslog \
 && apt-get -y install opendkim opendkim-tools

COPY postfix/ /postfix/
WORKDIR /postfix/
ENTRYPOINT ["./startup.sh"]
