FROM debian:bullseye-slim as stage2
RUN apt-get update && apt-get -y install python3 make g++ npm curl
RUN npm install --global yarn
RUN npm install -g n
RUN n 16.14.2
COPY cms/package.json cms/package.json
COPY cms/yarn.lock cms/yarn.lock
WORKDIR /cms/
RUN yarn
COPY cms/ /cms/
RUN yarn build
ENTRYPOINT ["yarn", "start"]
