import os

TIMELIMIT = int(os.getenv('TIMELIMIT'))
MAX_RAM = int(os.getenv('MAX_RAM'))
KAFKA_ADDR = os.getenv('KAFKA_HOST') + ':' + os.getenv('KAFKA_PORT')
MAX_ACTIVE_TASKS = int(os.getenv('MAX_ACTIVE_TASKS'))
DOCKER_NETWORK = os.getenv('DOCKER_NETWORK')
POSTGRES_HOST = os.getenv('POSTGRES_HOST')
POSTGRES_PORT = os.getenv('POSTGRES_PORT')
POSTGRES_USER = os.getenv('POSTGRES_USER')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')
POSTGRES_DBNAME = os.getenv('POSTGRES_DBNAME')
DB_TASKS_TABLE_NAME = os.getenv('DB_TASKS_TABLE_NAME')
